[package]
name = "gitlab-api"
version = "0.1.0"
edition = "2021"

[dependencies]
surf = "2.3.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.16", features = ["full"] }
async-trait = "0.1.52"